

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    url: jdbc:mysql://139.162.99.98:32651/20230114_macbook_boat_db03_ship
    username: 20230114_root
    password: 3A$LK@Pe5@jkTm^HFtR
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8913


group6:
  shipType:
    shipTypePageSize: 10